### ISSUE TITLE
Add an option to exclude nodes

### ISSUE THREAD

**Issue by OmerRochman** [francois-rozet/dawgz#10]
Add the option to exclude certain nodes so the jobs don't run on them.
A hack in schedulers.py:480 works, but it would be nice to have the option.

```
  text = subprocess.run(
      ['sbatch', '--parsable', '--exclude=compute-02',str(shfile)],
      capture_output=True,
      check=True,
      text=True,
  ).stdout

```

**Comment by francois-rozet** [comment]
Hello @OmerRochman, thank you for the feature request. I think you can already pass that setting with

```
@job(..., exclude='node-04')
```

or

```
schedule(..., exclude='node-04')
```

Tell me if it does not work.

**Comment by OmerRochman** [comment]
Works for 
```
@job(..., exclude='my-partition')
```

 so will probably work with exclude

**Comment by francois-rozet** [comment]
Ok, btw you can also select partitions with `partition='a5000,tesla'`
